[General]
SyntaxVersion=2
BeginHotkey=118
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=7fa776f7-dd5e-4fa2-a0d7-679af9445db0
Description=回到上一个存档
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
RunApp "C:\Users\ASUS\AppData\Roaming\DarkSoulsIII\011000011509cdf9\git-reset-hard-HEAD~1.bat"
