[General]
SyntaxVersion=2
BeginHotkey=119
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=771ebd0d-375a-4bec-92f7-fe044f9f2a58
Description=´æµµ
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
RunApp "C:\Users\ASUS\AppData\Roaming\DarkSoulsIII\011000011509cdf9\git-commit.bat"
