[General]
SyntaxVersion=2
BeginHotkey=118
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=f37058d2-8dac-4860-87fd-95ae7fa0417f
Description=回到上一个存档
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
RunApp "C:\Documents\NBGI\DARK SOULS REMASTERED\352964089\git-reset-hard-HEAD~1.bat"
